    <?php require_once "templates/header.phtml";?>
    <section>
        <title><h3>¿sabias que?</h3></title>
        <p>El consumo desmedido y el daño medioambiental han generado una gran preocupación en la sociedad. En contrapartida, el consumo responsable busca reducir el agotamiento de recursos no renovables, deterioro ambiental y cambio climático. Describe distintos indicadores que son, los beneficios, metas y desafíos viables, capaces de ser comprendidos por la sociedad (Mendiola, C. 2007).
            Los consumidores que buscan ser efectivos, eficientes, equitativos, equilibrados, racionales y solidarios, se encuentran dentro de la línea de pensamiento de lo que se considera un consumo responsable (Cortés Funes, 2011). Este tipo de consumo se sienta sobre la bases de la minimización del daño ambiental, la reducción del desperdicio de alimentos, y la utilización excesiva de los recursos no renovables. 
        </p>
    </section>
    <?php require_once "templates/footer.phtml";?>
</body>
</html>